name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16

      - name: Install dependencies
        run: cd frontend/ && npm install

      - name: Install nuxi
        run: npm i @nuxt/kit

      - name: Generate project
        run: cd frontend/ && npx nuxi generate

      - name: Set password for ssh
        run: sudo apt-get install sshpass && sshpass -p ${{ secrets.ROOT_PASSWORD }}
      
      - name: Deploy to remote server
        uses: easingthemes/ssh-deploy@v2.1.5
        env:
          REMOTE_HOST: ${{ secrets.SERVER_IP }}
          SSH_PRIVATE_KEY: ${{ secrets.KEY }}
          REMOTE_USER: root
          TARGET: /var/www/html
          SOURCE: frontend/.output/public